#!/usr/bin/env python3
import glob
import random
import sys
args = sys.argv[1:]
if len(args) == 0:
    args = [""]
walls = list()
for source in args:
    walls += glob.glob("/home/peter/Downloads/Wallpapers/" + source + "/*.*")
print(random.choice(walls))