#! /bin/sh

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0

nr_of_external_monitors=$(xrandr -q | grep '^DP' | grep ' connected' | wc -l)
if [[ $nr_of_external_monitors = 1 ]]; then
	connected_monitor=$(xrandr -q | grep '^DP' | grep ' connected' | awk '{print $1}')

	bspc monitor $connected_monitor -d 1 2 3 4 5 6 7 8 9 0 -f
	xrandr --output eDP-1 --mode 3840x2400 --output $connected_monitor --primary --mode 3840x2160 --right-of eDP-1

fi

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   40
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a urxvt desktop='1'

bspc rule -a firefox desktop='2' follow=on focus=on
bspc rule -a Chromium desktop='2' follow=on focus=on

### Chats
bspc rule -a Slack desktop='3'
bspc rule -a Skype desktop='3'

sxhkd &
picom &
dunst &
libinput-gestures-setup start
~/.config/polybar/launch.sh &
# lock screen after 10 mins of inactivity
xidlehook --not-when-fullscreen --not-when-audio --timer primary 300 'slock' '' &
feh --randomize --bg-fill ~/Downloads/Wallpapers &

wal -R

